## GOATESQUE https://medium.com/devopsturkiye/self-managed-argo-cd-app-of-everything-a226eb100cf0 ##
applications:
  argocd:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/Shasame/KinD-test-cluster.git
      path: argocd/argocd/argo-cd
      targetRevision: path
      helm:
        valueFiles:
        - values.yaml
        - ../values-argocd.yaml
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
  argocd-apps:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/Shasame/KinD-test-cluster.git
      path: argocd/argocd-apps
      targetRevision: path
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
  argocd-appprojects:
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      repoURL: https://github.com/Shasame/KinD-test-cluster.git
      path: argocd/projects
      targetRevision: path
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
projects:
  argocd:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: argocd project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist: 
    - group: '*'
      kind: '*'
    orphanedResources: 
      warn: false